"use client";

import { useState } from "react";
import { Info } from "lucide-react";
import { cn } from "@/lib/utils";

const LABELS: Record<string, string> = {
  match: "AI Match Score",
  readiness: "AI Readiness Assessment",
  draft: "AI-Generated Draft",
  strategy: "AI Strategy",
  chat: "AI Response",
};

const DESCRIPTIONS: Record<string, string> = {
  match:
    "This match score was generated by AI based on alignment between your organization profile and the grant's criteria. It is an estimate — not a guarantee of eligibility or award probability.",
  readiness:
    "This readiness assessment was generated by AI based on your uploaded documents and profile data. Review all items carefully before applying.",
  draft:
    "This grant application draft was generated by AI using your organization's information. You must review, edit, and verify all content before submitting to any funder.",
  strategy:
    "This strategy recommendation was generated by AI. It is a starting point — consult with a grant professional before acting on strategic advice.",
  chat:
    "Grantie is an AI assistant. Its responses are generated by a language model and may contain errors. Do not rely on Grantie for legal or financial advice.",
};

interface AIDisclosureProps {
  type: "match" | "readiness" | "draft" | "strategy" | "chat";
  className?: string;
}

export function AIDisclosure({ type, className }: AIDisclosureProps) {
  const [open, setOpen] = useState(false);

  return (
    <div className={cn("relative inline-flex items-center", className)}>
      <button
        onClick={() => setOpen((v) => !v)}
        aria-label="AI-generated content — click for details"
        className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300 hover:bg-amber-200 dark:hover:bg-amber-900/50 transition-colors"
      >
        <Info className="h-3 w-3 shrink-0" />
        AI-Generated &middot; Review before use
      </button>

      {open && (
        <>
          {/* Backdrop to close on outside click */}
          <div
            className="fixed inset-0 z-40"
            onClick={() => setOpen(false)}
            aria-hidden="true"
          />
          <div
            role="tooltip"
            className="absolute bottom-full left-0 mb-2 z-50 w-72 p-3 rounded-lg bg-white dark:bg-warm-800 border border-warm-200 dark:border-warm-700 shadow-lg text-xs text-warm-700 dark:text-warm-300 leading-relaxed"
          >
            <p className="font-semibold text-warm-900 dark:text-warm-50 mb-1">{LABELS[type]}</p>
            <p>{DESCRIPTIONS[type]}</p>
            <a
              href="/terms#ai-disclosure"
              className="mt-2 inline-block text-brand-teal hover:underline"
              onClick={() => setOpen(false)}
            >
              Learn more in our Terms of Service
            </a>
          </div>
        </>
      )}
    </div>
  );
}
