import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — GrantIQ",
  description: "Terms governing your use of the GrantIQ platform.",
};

export default function TermsOfServicePage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-16 text-warm-800 dark:text-warm-200">
      <h1 className="text-3xl font-bold text-warm-900 dark:text-warm-50 mb-2">Terms of Service</h1>
      <p className="text-sm text-warm-500 mb-10">Last updated: March 2026 &mdash; Effective upon account creation</p>

      <p className="text-sm mb-8 text-warm-600 dark:text-warm-400">
        These Terms of Service ("Terms") govern your access to and use of GrantIQ, operated by Friedman Global LLC
        ("Company," "we," "us," or "our"). By creating an account or using any part of GrantIQ, you agree to these
        Terms. If you do not agree, do not use the platform.
      </p>

      <Section title="1. Service Description">
        <p>
          GrantIQ is an AI-powered grant discovery, matching, strategy, and writing platform. The service includes:
        </p>
        <ul className="list-disc pl-5 space-y-1 mt-3">
          <li>AI-generated grant matching and scoring based on your organization profile</li>
          <li>Grant application drafting and editing assistance</li>
          <li>Readiness assessments and gap analysis</li>
          <li>Grant pipeline management and deadline tracking</li>
          <li>Nonprofit formation document preparation (where subscribed)</li>
          <li>AI strategy recommendations and advisor chat (Grantie)</li>
        </ul>
      </Section>

      <Section title="2. Account Responsibility">
        <p>
          You are responsible for the accuracy and completeness of all information you provide, including your
          organization profile, financial data, EIN, board information, and uploaded documents. GrantIQ's AI systems
          rely on this information to generate match scores, readiness assessments, and grant drafts. Providing
          inaccurate information may result in poor recommendations and does not constitute grounds for a refund.
        </p>
        <p className="mt-3">
          You are responsible for maintaining the security of your account credentials and for all activity that occurs
          under your account. Notify us immediately at{" "}
          <a href="mailto:support@grantiq.com" className="text-brand-teal hover:underline">
            support@grantiq.com
          </a>{" "}
          if you suspect unauthorized access.
        </p>
      </Section>

      <Section title="3. AI Disclosure">
        <div className="p-4 rounded-lg bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800">
          <p className="font-semibold text-amber-900 dark:text-amber-100 mb-2">Important: AI-Generated Content</p>
          <p>
            Grant applications, match scores, readiness assessments, and strategy recommendations are generated by
            artificial intelligence. Users must review and verify all AI-generated content before submission to any
            funder. GrantIQ does not review or edit AI-generated content on your behalf prior to submission.
          </p>
        </div>
        <p className="mt-4">
          AI outputs may contain errors, omissions, or content that does not accurately reflect your organization's work.
          You are solely responsible for the accuracy and completeness of any grant application submitted to a funder.
        </p>
      </Section>

      <Section title="4. No Guarantee of Funding">
        <div className="p-4 rounded-lg bg-warm-100 dark:bg-warm-800 border border-warm-200 dark:border-warm-700">
          <p>
            GrantIQ does not guarantee grant funding or application success. Match scores are AI-generated estimates
            based on alignment between your profile and grant criteria — they are not predictions of award probability.
            Funders have full discretion in their award decisions, which are outside our control.
          </p>
        </div>
      </Section>

      <Section title="5. Success Fees">
        <p>
          Certain GrantIQ plans include a success fee model in addition to or in lieu of subscription pricing. The
          following terms apply:
        </p>
        <ul className="list-disc pl-5 space-y-2 mt-3">
          <li>
            <strong>Fee range:</strong> Success fees range from 4% to 10% of awarded grant funds, as specified in your
            plan or service agreement.
          </li>
          <li>
            <strong>Minimum fee:</strong> A minimum success fee applies per award as specified at the time of enrollment
            or in your service agreement.
          </li>
          <li>
            <strong>Reporting obligation:</strong> You agree to notify GrantIQ within 14 days of receiving notice of a
            grant award for any application initiated through the platform.
          </li>
          <li>
            <strong>Payment timing:</strong> Success fees are due within 30 days of receiving awarded funds.
          </li>
          <li>
            <strong>Invoicing:</strong> GrantIQ will issue an invoice via Stripe upon notification of an award. Invoices
            not paid within 30 days accrue interest at 1.5% per month.
          </li>
          <li>
            <strong>Scope:</strong> Success fees apply only to grants where GrantIQ's platform was used to initiate,
            draft, or materially assist with the application.
          </li>
        </ul>
      </Section>

      <Section title="6. Nonprofit Formation Services">
        <div className="p-4 rounded-lg bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800">
          <p>
            GrantIQ is not a law firm and does not provide legal advice. Nonprofit formation services use standardized
            templates and document preparation assistance. The information and documents provided do not constitute legal
            advice and do not create an attorney-client relationship. We strongly recommend consulting a licensed
            attorney before filing formation documents.
          </p>
        </div>
        <p className="mt-4">
          GrantIQ is not responsible for the rejection of formation documents by any state or federal agency. Filing
          fees, state fees, and IRS fees are the sole responsibility of the user.
        </p>
      </Section>

      <Section title="7. Payment Terms">
        <ul className="list-disc pl-5 space-y-2">
          <li>
            <strong>Subscription billing:</strong> Paid plans are billed via Stripe on a monthly or annual basis.
            Subscriptions automatically renew unless canceled at least 24 hours before the renewal date.
          </li>
          <li>
            <strong>Refunds:</strong> Monthly subscriptions are non-refundable. Annual subscriptions may receive a
            prorated refund within 30 days of initial purchase if requested and no AI-generated applications have been
            submitted to funders. Contact{" "}
            <a href="mailto:support@grantiq.com" className="text-brand-teal hover:underline">
              support@grantiq.com
            </a>{" "}
            to request a refund.
          </li>
          <li>
            <strong>Plan changes:</strong> Upgrades take effect immediately; downgrades take effect at the next billing
            cycle.
          </li>
          <li>
            <strong>Failed payments:</strong> If a payment fails, access may be restricted until payment is resolved.
            We will attempt to notify you at the email on file.
          </li>
        </ul>
      </Section>

      <Section title="8. Intellectual Property">
        <ul className="list-disc pl-5 space-y-2">
          <li>
            <strong>Your content:</strong> You own all content you upload or create using GrantIQ, including grant
            applications, documents, and organization data. You grant GrantIQ a limited license to process and store
            your content to provide the service.
          </li>
          <li>
            <strong>AI-generated content:</strong> Grant drafts and other content generated by the AI using your inputs
            are owned by you upon creation.
          </li>
          <li>
            <strong>Our platform:</strong> GrantIQ owns all rights to the platform, algorithms, interfaces, scoring
            models, and underlying technology. You may not copy, reverse-engineer, or create derivative works from any
            part of the platform.
          </li>
          <li>
            <strong>Feedback:</strong> If you provide feedback or suggestions, we may use them to improve the platform
            without obligation to you.
          </li>
        </ul>
      </Section>

      <Section title="9. Limitation of Liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, GRANTIQ AND FRIEDMAN GLOBAL LLC SHALL NOT BE LIABLE FOR
          ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST GRANT
          FUNDING, DATA LOSS, OR BUSINESS INTERRUPTION, ARISING FROM YOUR USE OF OR INABILITY TO USE THE PLATFORM,
          REGARDLESS OF THE THEORY OF LIABILITY.
        </p>
        <p className="mt-3">
          OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM OR RELATED TO THESE TERMS OR THE PLATFORM SHALL NOT
          EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM OR (B) $100.
        </p>
      </Section>

      <Section title="10. Dispute Resolution">
        <p>
          You and GrantIQ agree to resolve any dispute, claim, or controversy arising from these Terms or your use of
          the platform through binding arbitration administered by the American Arbitration Association under its
          Consumer Arbitration Rules, rather than in court, except for claims that may be brought in small claims court.
        </p>
        <p className="mt-3">
          <strong>Class action waiver:</strong> You agree to resolve disputes on an individual basis and waive the right
          to participate in a class action lawsuit or class-wide arbitration.
        </p>
        <p className="mt-3">
          These Terms are governed by the laws of the State of Georgia, without regard to its conflict of law provisions.
        </p>
      </Section>

      <Section title="11. Termination">
        <ul className="list-disc pl-5 space-y-2">
          <li>
            <strong>By you:</strong> You may cancel your account at any time through account settings. Cancellation
            takes effect at the end of the current billing period.
          </li>
          <li>
            <strong>By us:</strong> We may suspend or terminate your account for violations of these Terms, non-payment,
            fraudulent activity, or misuse of the platform. We will provide notice when practicable.
          </li>
          <li>
            <strong>Data on termination:</strong> Upon account termination or cancellation, your data will be retained
            for 30 days during which you may request an export. After 30 days, your personal data will be deleted per
            our Privacy Policy. Anonymized, aggregate data may be retained.
          </li>
        </ul>
      </Section>

      <Section title="12. Modifications to Terms">
        <p>
          We may modify these Terms at any time. For material changes, we will provide at least 30 days' advance notice
          by email and/or a prominent notice in the platform. Continued use of GrantIQ after the effective date of
          changes constitutes acceptance of the updated Terms. If you do not agree to the changes, you must stop using
          the platform and cancel your subscription before the effective date.
        </p>
      </Section>

      <Section title="13. Miscellaneous">
        <ul className="list-disc pl-5 space-y-2">
          <li>These Terms constitute the entire agreement between you and GrantIQ regarding the platform.</li>
          <li>If any provision is found unenforceable, the remainder of the Terms remains in effect.</li>
          <li>Our failure to enforce any provision does not waive our right to enforce it in the future.</li>
          <li>You may not assign your rights under these Terms without our written consent.</li>
        </ul>
      </Section>

      <div className="mt-12 p-4 rounded-lg bg-warm-100 dark:bg-warm-800 text-sm text-warm-600 dark:text-warm-400">
        <strong>Questions?</strong> Contact Friedman Global LLC / GrantIQ at{" "}
        <a href="mailto:support@grantiq.com" className="text-brand-teal hover:underline">
          support@grantiq.com
        </a>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-semibold text-warm-900 dark:text-warm-50 mb-3 pb-2 border-b border-warm-200 dark:border-warm-700">
        {title}
      </h2>
      <div className="text-sm leading-relaxed text-warm-700 dark:text-warm-300">{children}</div>
    </section>
  );
}
