export interface IndustryProfile {
  industry: string;
  painPoints: string[];
  recommendedGrantTypes: string[];
  recommendedServiceTier: string;
  grantKeywords: string[];
  tips: string[];
}

export const INDUSTRY_PROFILES: Record<string, IndustryProfile> = {
  airlines_aviation: {
    industry: "Airlines / Aviation",
    painPoints: ["FAA grant complexity", "Infrastructure modernization funding gaps"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["aviation", "FAA", "airport", "air transportation", "aerospace infrastructure"],
    tips: ["FAA Airport Improvement Program (AIP) is the primary federal source", "State aviation departments often match federal grants"],
  },
  alternative_dispute_resolution: {
    industry: "Alternative Dispute Resolution",
    painPoints: ["Limited awareness of justice-sector grants", "Narrow eligibility for legal aid funding"],
    recommendedGrantTypes: ["foundation", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["mediation", "conflict resolution", "access to justice", "legal services", "dispute resolution"],
    tips: ["DOJ and state bar foundations fund ADR programs", "Frame impact around court decongestion and cost savings"],
  },
  alternative_medicine: {
    industry: "Alternative Medicine",
    painPoints: ["NIH NCCIH funding competition", "Difficulty meeting clinical evidence requirements"],
    recommendedGrantTypes: ["federal", "foundation"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["integrative medicine", "NCCIH", "complementary health", "holistic", "wellness research"],
    tips: ["NIH's National Center for Complementary and Integrative Health is primary funder", "Pilot studies increase success rates for larger NIH grants"],
  },
  animation: {
    industry: "Animation",
    painPoints: ["Limited federal arts funding", "State arts agency grant competition"],
    recommendedGrantTypes: ["foundation", "state", "corporate"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["animation", "digital arts", "creative media", "film", "arts production"],
    tips: ["NEA and state arts councils fund animation with educational components", "Corporate media grants (Google, Adobe) support digital creative fields"],
  },
  apparel_fashion: {
    industry: "Apparel & Fashion",
    painPoints: ["Workforce training funding gaps", "Sustainable manufacturing grant navigation"],
    recommendedGrantTypes: ["state", "federal", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["apparel", "fashion", "textile", "workforce development", "sustainable manufacturing"],
    tips: ["EDA and SBA grants support small apparel manufacturers", "Sustainability-focused grants available through EPA and state programs"],
  },
  architecture_planning: {
    industry: "Architecture & Planning",
    painPoints: ["HUD and community development grant complexity", "Historic preservation funding access"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["architecture", "urban planning", "historic preservation", "HUD", "community development"],
    tips: ["HUD Community Development Block Grants support architecture/planning projects", "National Trust for Historic Preservation offers targeted grants"],
  },
  arts_crafts: {
    industry: "Arts And Crafts",
    painPoints: ["NEA/state arts grant competitiveness", "Documenting cultural impact for funders"],
    recommendedGrantTypes: ["foundation", "state", "federal"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["arts", "crafts", "cultural", "NEA", "state arts council", "handmade", "artisan"],
    tips: ["State arts agencies often have less competition than NEA direct grants", "Document economic impact of local arts to strengthen applications"],
  },
  automotive: {
    industry: "Automotive",
    painPoints: ["EV transition funding navigation", "Workforce development grant eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["automotive", "electric vehicle", "EV", "workforce training", "advanced manufacturing", "DOE"],
    tips: ["DOE and EPA offer substantial grants for EV and clean vehicle transition", "State workforce boards fund automotive technician training programs"],
  },
  aviation_aerospace: {
    industry: "Aviation & Aerospace",
    painPoints: ["SBIR/STTR aerospace competition", "Defense contract readiness requirements"],
    recommendedGrantTypes: ["federal"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["aerospace", "aviation", "SBIR", "STTR", "NASA", "DoD", "FAA", "space technology"],
    tips: ["NASA SBIR/STTR is the top funding path for aerospace innovators", "SAM.gov registration is mandatory for most aerospace federal grants"],
  },
  banking: {
    industry: "Banking",
    painPoints: ["CDFI certification complexity", "Community reinvestment grant alignment"],
    recommendedGrantTypes: ["federal", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["CDFI", "community development finance", "CRA", "financial inclusion", "underserved communities"],
    tips: ["CDFI Fund awards are the primary federal source for mission-driven banks", "CRA credit can be tied to foundation partnership grants"],
  },
  biotechnology: {
    industry: "Biotechnology",
    painPoints: ["NIH application complexity and competition", "SBIR Phase II bridge funding gaps"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["biotech", "NIH", "SBIR", "STTR", "life sciences", "bioscience", "R&D", "clinical research"],
    tips: ["NIH SBIR Phase I is the fastest entry point for biotech startups", "State biotech councils often provide matching or pre-SBIR funding"],
  },
  broadcast_media: {
    industry: "Broadcast Media",
    painPoints: ["CPB and public media grant eligibility", "Local journalism funding scarcity"],
    recommendedGrantTypes: ["federal", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["broadcast", "public media", "CPB", "journalism", "local news", "media"],
    tips: ["Corporation for Public Broadcasting funds public radio and TV stations", "Local journalism foundations (Knight, MacArthur) fund community news"],
  },
  building_materials: {
    industry: "Building Materials",
    painPoints: ["Infrastructure grant eligibility criteria", "Workforce training program access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["building materials", "construction", "infrastructure", "manufacturing", "workforce training"],
    tips: ["DOC Manufacturing Extension Partnership supports materials manufacturers", "IIJA infrastructure bill created new funding streams for materials suppliers"],
  },
  business_supplies: {
    industry: "Business Supplies And Equipment",
    painPoints: ["Small business grant eligibility limits", "Economic development program access"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["small business", "equipment", "economic development", "SBA", "business supplies"],
    tips: ["SBA Small Business Investment Company (SBIC) supports equipment financing", "State small business development centers offer grant referrals"],
  },
  chemicals: {
    industry: "Chemicals",
    painPoints: ["EPA green chemistry grant requirements", "DOE industrial decarbonization funding"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["chemicals", "green chemistry", "EPA", "DOE", "industrial", "sustainability", "decarbonization"],
    tips: ["EPA Safer Choice program and green chemistry grants reward sustainable practices", "DOE industrial efficiency grants cover chemical manufacturing processes"],
  },
  civic_social: {
    industry: "Civic & Social Organization",
    painPoints: ["Foundation grant competition", "Demonstrating measurable community impact"],
    recommendedGrantTypes: ["foundation", "federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["civic", "community", "social services", "nonprofits", "community development"],
    tips: ["Community foundations are often the most accessible funders for civic orgs", "CDBG (Community Development Block Grants) fund many civic programs"],
  },
  civil_engineering: {
    industry: "Civil Engineering",
    painPoints: ["Federal infrastructure grant complexity", "State DOT contract eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["civil engineering", "infrastructure", "DOT", "transportation", "water", "IIJA"],
    tips: ["IIJA (Infrastructure Investment and Jobs Act) created massive new funding", "State DOT programs often have DBE set-asides for small civil engineering firms"],
  },
  commercial_real_estate: {
    industry: "Commercial Real Estate",
    painPoints: ["Opportunity Zone incentive navigation", "Historic tax credit complexity"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["real estate", "opportunity zone", "historic tax credit", "HUD", "community development"],
    tips: ["Historic Tax Credits (HTC) provide 20% credit for qualifying rehabilitation", "New Markets Tax Credits subsidize development in low-income areas"],
  },
  computer_security: {
    industry: "Computer & Network Security",
    painPoints: ["CISA and DHS cybersecurity grant access", "SBIR cybersecurity competition"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["cybersecurity", "CISA", "DHS", "SBIR", "network security", "cyber defense"],
    tips: ["CISA State and Local Cybersecurity Grant Program funds infrastructure upgrades", "DHS SBIR solicitations regularly include cybersecurity topics"],
  },
  computer_games: {
    industry: "Computer Games",
    painPoints: ["Limited traditional grant access", "NEA digital arts grant navigation"],
    recommendedGrantTypes: ["state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["game development", "interactive media", "digital arts", "entertainment technology", "simulation"],
    tips: ["State film offices sometimes fund serious games and educational games", "NSF funds games with STEM education components"],
  },
  computer_hardware: {
    industry: "Computer Hardware",
    painPoints: ["DOD and DARPA SBIR competition", "Advanced manufacturing grant eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["computer hardware", "semiconductors", "electronics", "DARPA", "SBIR", "advanced manufacturing"],
    tips: ["DOD SBIR solicitations often include hardware and embedded systems topics", "CHIPS Act created new funding for domestic semiconductor and hardware manufacturing"],
  },
  computer_networking: {
    industry: "Computer Networking",
    painPoints: ["Broadband grant eligibility requirements", "NTIA program complexity"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["networking", "broadband", "NTIA", "telecommunications", "internet infrastructure", "connectivity"],
    tips: ["NTIA BEAD program is the largest broadband funding opportunity ever", "FCC E-Rate funds networking for schools and libraries"],
  },
  computer_software: {
    industry: "Computer Software",
    painPoints: ["SBIR/STTR navigation complexity", "R&D tax credit overlap confusion"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["software", "SBIR", "STTR", "R&D", "technology", "innovation", "SaaS"],
    tips: ["SBIR Phase I is the fastest path to non-dilutive federal funding for software", "Many states offer R&D tax credits that stack with federal SBIR awards"],
  },
  construction: {
    industry: "Construction",
    painPoints: ["Infrastructure grant eligibility requirements", "Workforce development funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["construction", "infrastructure", "workforce development", "IIJA", "DOT", "HUD"],
    tips: ["IIJA created the largest construction funding surge in decades", "DOL apprenticeship grants fund construction workforce training programs"],
  },
  consumer_electronics: {
    industry: "Consumer Electronics",
    painPoints: ["SBIR and DOE funding competition", "Advanced manufacturing grant navigation"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["consumer electronics", "SBIR", "DOE", "advanced manufacturing", "innovation", "R&D"],
    tips: ["DOE Office of Energy Efficiency funds consumer electronics efficiency work", "NIST Manufacturing Extension Partnership supports electronics manufacturers"],
  },
  consumer_goods: {
    industry: "Consumer Goods",
    painPoints: ["Small manufacturer grant access", "Export promotion funding navigation"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["consumer goods", "manufacturing", "export", "small business", "product development"],
    tips: ["SBA State Trade Expansion Program (STEP) grants fund export activities", "State economic development agencies fund consumer goods manufacturers"],
  },
  consumer_services: {
    industry: "Consumer Services",
    painPoints: ["Limited sector-specific grants", "Workforce training eligibility requirements"],
    recommendedGrantTypes: ["state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["consumer services", "workforce training", "small business", "service industry"],
    tips: ["State workforce development boards fund service sector training", "Community development grants support consumer services in underserved areas"],
  },
  cosmetics: {
    industry: "Cosmetics",
    painPoints: ["Clean beauty R&D funding gaps", "Minority-owned beauty brand grant access"],
    recommendedGrantTypes: ["foundation", "state", "corporate"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["cosmetics", "beauty", "personal care", "minority-owned", "women-owned", "small business"],
    tips: ["Corporate grants from major beauty companies support minority-owned beauty businesses", "SBA funding programs prioritize women- and minority-owned cosmetics businesses"],
  },
  dairy: {
    industry: "Dairy",
    painPoints: ["USDA dairy program complexity", "Conservation grant eligibility requirements"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["dairy", "USDA", "agriculture", "conservation", "EQIP", "farm bill"],
    tips: ["USDA EQIP conservation payments are accessible to most dairy operations", "Farm Service Agency offers dairy-specific loan and grant programs"],
  },
  defense_space: {
    industry: "Defense & Space",
    painPoints: ["DARPA/DoD SBIR proposal complexity", "Security clearance grant requirements"],
    recommendedGrantTypes: ["federal"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["defense", "space", "DARPA", "DoD", "SBIR", "STTR", "national security", "NASA"],
    tips: ["SBIR.gov is the central hub for DoD and NASA small business funding", "Facility security clearance requirements should be planned early"],
  },
  design: {
    industry: "Design",
    painPoints: ["NEA and state arts funding competition", "Social impact design grant access"],
    recommendedGrantTypes: ["foundation", "state", "corporate"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["design", "graphic design", "UX", "industrial design", "arts", "creative"],
    tips: ["AIGA and design foundations fund community-centered design projects", "NEA Our Town grants support design projects with civic impact"],
  },
  elearning: {
    industry: "E-Learning",
    painPoints: ["DOE education technology grant competition", "Rural broadband requirement for funding"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["e-learning", "education technology", "edtech", "online learning", "DOE", "workforce training"],
    tips: ["DOL TAACCCT and WIOA fund workforce-focused e-learning programs", "State departments of education have dedicated edtech grant programs"],
  },
  education_management: {
    industry: "Education Management",
    painPoints: ["Title I and Title funding changes", "State education grant competition"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["education", "Title I", "DOE", "school management", "curriculum", "student achievement"],
    tips: ["Title grants require direct partnership with local education agencies (LEAs)", "Gates Foundation and Walton Family Foundation are key private funders"],
  },
  electrical_manufacturing: {
    industry: "Electrical/Electronic Manufacturing",
    painPoints: ["DOE advanced manufacturing grant complexity", "Workforce training program navigation"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["electrical", "electronics", "manufacturing", "DOE", "NIST", "advanced manufacturing", "workforce"],
    tips: ["DOE Advanced Manufacturing Office funds electrical manufacturing R&D", "NIST MEP centers offer grant navigation for small manufacturers"],
  },
  entertainment: {
    industry: "Entertainment",
    painPoints: ["NEA and state arts grant competition", "Cultural industry funding gaps"],
    recommendedGrantTypes: ["state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["entertainment", "arts", "cultural", "performance", "NEA", "state arts council"],
    tips: ["State arts councils fund entertainment with cultural/community components", "Community development grants support entertainment in underserved areas"],
  },
  environmental_services: {
    industry: "Environmental Services",
    painPoints: ["EPA grant eligibility complexity", "Environmental justice funding access"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["environmental", "EPA", "sustainability", "conservation", "environmental justice", "clean energy"],
    tips: ["EPA Environmental Justice Collaborative Problem-Solving grants target disadvantaged areas", "USDA Rural Development funds environmental services in rural communities"],
  },
  facilities_services: {
    industry: "Facilities Services",
    painPoints: ["Limited sector-specific grants", "Energy efficiency incentive navigation"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["facilities management", "energy efficiency", "building operations", "sustainability"],
    tips: ["DOE Better Buildings program supports energy-efficient facilities projects", "State energy offices offer rebates and grants for facilities upgrades"],
  },
  farming: {
    industry: "Farming",
    painPoints: ["USDA program complexity", "Beginning farmer funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["farming", "USDA", "agriculture", "NRCS", "EQIP", "FSA", "beginning farmer"],
    tips: ["USDA Beginning Farmer and Rancher program is highly accessible", "NRCS EQIP pays farmers for implementing conservation practices"],
  },
  financial_services: {
    industry: "Financial Services",
    painPoints: ["CDFI fund eligibility requirements", "Financial inclusion grant competition"],
    recommendedGrantTypes: ["federal", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["financial services", "CDFI", "financial inclusion", "community lending", "fintech"],
    tips: ["CDFI certification opens doors to Treasury and foundation funding", "JPMorganChase and Bank of America foundations fund financial inclusion"],
  },
  fine_art: {
    industry: "Fine Art",
    painPoints: ["NEA direct grant competition", "State arts agency funding limitations"],
    recommendedGrantTypes: ["foundation", "state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["fine art", "visual art", "NEA", "state arts council", "gallery", "artist"],
    tips: ["Artist fellowships from state arts agencies are the most accessible entry point", "Private foundations (Pollock-Krasner, Guggenheim) fund individual artists"],
  },
  fishery: {
    industry: "Fishery",
    painPoints: ["NOAA grant complexity", "Aquaculture program eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["fishery", "aquaculture", "NOAA", "fishing", "coastal", "marine"],
    tips: ["NOAA Sea Grant funds fishery and aquaculture research and commercialization", "State coastal programs and Sea Grant extensions provide local support"],
  },
  food_beverages: {
    industry: "Food & Beverages",
    painPoints: ["USDA value-added grant competition", "Food safety compliance funding gaps"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["food", "beverage", "USDA", "value-added", "local food", "food system", "agriculture"],
    tips: ["USDA Value-Added Producer Grants support food and beverage product development", "Local and regional food system grants support farm-to-table operations"],
  },
  food_production: {
    industry: "Food Production",
    painPoints: ["USDA processing grant access", "Rural business development funding"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["food production", "food processing", "USDA", "rural development", "manufacturing", "food safety"],
    tips: ["USDA Rural Business Development Grants support food processing enterprises", "FDA offers compliance and food safety technical assistance grants"],
  },
  furniture: {
    industry: "Furniture",
    painPoints: ["Manufacturing grant eligibility requirements", "Export promotion funding access"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["furniture", "manufacturing", "woodworking", "export", "small business", "craftsmanship"],
    tips: ["NIST MEP centers help small furniture manufacturers access grants", "SBA STEP grants fund furniture export activities"],
  },
  glass_ceramics: {
    industry: "Glass, Ceramics & Concrete",
    painPoints: ["Advanced materials grant eligibility", "Workforce training access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["glass", "ceramics", "concrete", "advanced materials", "manufacturing", "DOE"],
    tips: ["DOE Advanced Manufacturing Office funds advanced materials development", "State manufacturing extension programs support smaller producers"],
  },
  government_admin: {
    industry: "Government Administration",
    painPoints: ["Federal grant match requirements", "Multi-agency coordination complexity"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["government", "public administration", "federal grants", "ARPA", "infrastructure", "community development"],
    tips: ["ARPA (American Rescue Plan) funds are still being deployed through state governments", "EDA and HUD programs often require government co-applicants"],
  },
  graphic_design: {
    industry: "Graphic Design",
    painPoints: ["Limited direct grant funding", "Arts-adjacent grant eligibility"],
    recommendedGrantTypes: ["foundation", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["graphic design", "visual communication", "arts", "creative industry", "design"],
    tips: ["Frame proposals around community impact and education to access arts grants", "Corporate design grants from Adobe and Figma support creative professionals"],
  },
  health_wellness: {
    industry: "Health, Wellness And Fitness",
    painPoints: ["HRSA and CDC grant application complexity", "Chronic disease prevention funding competition"],
    recommendedGrantTypes: ["federal", "foundation", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["health", "wellness", "fitness", "prevention", "HRSA", "CDC", "chronic disease", "community health"],
    tips: ["CDC Community Health Worker grants fund wellness program delivery", "HRSA Health Center Fund is the largest federal health access program"],
  },
  higher_education: {
    industry: "Higher Education",
    painPoints: ["Federal Title III/V funding competition", "Research grant indirect cost recovery"],
    recommendedGrantTypes: ["federal", "foundation", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["higher education", "Title III", "Title V", "STEM", "research", "workforce", "college", "university"],
    tips: ["Title III and V programs specifically support minority-serving institutions", "NSF ADVANCE and similar programs support STEM at academic institutions"],
  },
  hospital_healthcare: {
    industry: "Hospital & Health Care",
    painPoints: ["NIH application complexity", "Healthcare workforce grant eligibility"],
    recommendedGrantTypes: ["federal", "foundation", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["hospital", "healthcare", "NIH", "HRSA", "clinical", "patient care", "health services"],
    tips: ["HRSA programs are the most accessible federal health system grants", "Robert Wood Johnson Foundation is the largest private healthcare funder"],
  },
  hospitality: {
    industry: "Hospitality",
    painPoints: ["Tourism recovery grant eligibility", "Workforce training funding access"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["hospitality", "tourism", "hotel", "restaurant", "workforce training", "travel"],
    tips: ["EDA Tourism Promotion and Development grants fund hospitality recovery", "State tourism development offices administer hospitality-specific programs"],
  },
  human_resources: {
    industry: "Human Resources",
    painPoints: ["Limited direct HR sector grants", "Workforce development funding access"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["human resources", "workforce development", "WIOA", "training", "talent"],
    tips: ["WIOA funds employer-driven workforce development programs", "DOL grants often target HR programs serving underemployed populations"],
  },
  import_export: {
    industry: "Import And Export",
    painPoints: ["Export promotion grant eligibility", "Trade finance assistance navigation"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["import", "export", "trade", "SBA STEP", "international trade", "EXIM Bank"],
    tips: ["SBA STEP grants are the primary vehicle for small business export funding", "EXIM Bank and state trade offices provide matching support"],
  },
  family_services: {
    industry: "Individual & Family Services",
    painPoints: ["HHS grant complexity", "Child welfare and family support funding access"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["family services", "child welfare", "HHS", "ACF", "social services", "community support"],
    tips: ["HHS Administration for Children and Families is the primary federal funder", "United Way and community foundations fund local family service organizations"],
  },
  industrial_automation: {
    industry: "Industrial Automation",
    painPoints: ["DOE and NIST advanced manufacturing grant access", "Workforce training program eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["automation", "robotics", "advanced manufacturing", "NIST", "DOE", "Industry 4.0"],
    tips: ["NIST Advanced Manufacturing programs fund industrial automation innovation", "DOE Manufacturing USA institutes offer partnership funding"],
  },
  information_services: {
    industry: "Information Services",
    painPoints: ["Data access and privacy grant limitations", "Library and archival funding competition"],
    recommendedGrantTypes: ["federal", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["information services", "data", "library", "IMLS", "open data", "digital access"],
    tips: ["IMLS (Institute of Museum and Library Services) funds information access programs", "NSF data infrastructure grants support large-scale information initiatives"],
  },
  it_services: {
    industry: "Information Technology And Services",
    painPoints: ["SBIR/STTR navigation complexity", "Digital equity grant access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["IT", "technology", "SBIR", "digital equity", "cloud", "cybersecurity", "software"],
    tips: ["SBIR is the primary federal non-dilutive funding path for IT companies", "State digital equity plans create new IT service contract and grant opportunities"],
  },
  insurance: {
    industry: "Insurance",
    painPoints: ["Financial inclusion grant eligibility", "Insurance access program funding"],
    recommendedGrantTypes: ["foundation", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["insurance", "financial inclusion", "risk management", "CDFI", "underserved communities"],
    tips: ["Frame insurance initiatives around consumer protection to access foundation grants", "Federal programs fund community insurance access in disaster-prone areas"],
  },
  international_affairs: {
    industry: "International Affairs",
    painPoints: ["State Department grant complexity", "USAID proposal requirements"],
    recommendedGrantTypes: ["federal", "foundation"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["international affairs", "diplomacy", "USAID", "State Department", "global development", "democracy"],
    tips: ["USAID and State Department grants require strong international track record", "Private foundations (Gates, Ford, Soros) fund international affairs organizations"],
  },
  international_trade: {
    industry: "International Trade And Development",
    painPoints: ["EDA grant eligibility requirements", "Trade development funding complexity"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["international trade", "trade development", "export", "EDA", "SBA STEP", "global markets"],
    tips: ["EDA grants support trade-oriented economic development initiatives", "State international trade offices administer matching trade grants"],
  },
  internet: {
    industry: "Internet",
    painPoints: ["SBIR digital innovation competition", "Broadband and connectivity grant access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["internet", "broadband", "connectivity", "SBIR", "digital", "NTIA", "FCC"],
    tips: ["NTIA and FCC programs fund internet access and innovation projects", "SBIR Phase I is fastest non-dilutive funding path for internet startups"],
  },
  law_enforcement: {
    industry: "Law Enforcement",
    painPoints: ["BJA and COPS grant complexity", "Equipment and technology funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["law enforcement", "police", "public safety", "BJA", "COPS", "DOJ", "community policing"],
    tips: ["DOJ COPS Hiring Program is the primary federal hiring grant for law enforcement", "BJA Bulletproof Vest Partnership and equipment grants are accessible entry points"],
  },
  legal_services: {
    industry: "Legal Services",
    painPoints: ["LSC grant eligibility requirements", "Access-to-justice funding competition"],
    recommendedGrantTypes: ["federal", "foundation", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["legal services", "legal aid", "LSC", "access to justice", "pro bono", "civil legal"],
    tips: ["Legal Services Corporation is the largest funder of civil legal aid in the US", "State bar foundations and IOLTA programs are key secondary funders"],
  },
  leisure_travel: {
    industry: "Leisure, Travel & Tourism",
    painPoints: ["EDA tourism grant eligibility", "Rural tourism development funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["tourism", "travel", "leisure", "EDA", "rural development", "hospitality"],
    tips: ["EDA Tourism Promotion grants focus on regional economic development through tourism", "USDA Rural Development funds rural tourism infrastructure"],
  },
  libraries: {
    industry: "Libraries",
    painPoints: ["IMLS grant competition", "State library funding changes"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["library", "IMLS", "public library", "digital literacy", "community access", "information access"],
    tips: ["IMLS Grants to States is the primary federal funding stream for libraries", "Bill & Melinda Gates Foundation historically funds library technology programs"],
  },
  logistics: {
    industry: "Logistics And Supply Chain",
    painPoints: ["Infrastructure grant eligibility", "Supply chain resilience funding navigation"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["logistics", "supply chain", "freight", "DOT", "infrastructure", "IIJA"],
    tips: ["DOT INFRA grants fund multimodal freight and logistics infrastructure", "IIJA created new supply chain resilience and port funding programs"],
  },
  luxury_goods: {
    industry: "Luxury Goods & Jewelry",
    painPoints: ["Limited direct grant access", "Export and artisan program eligibility"],
    recommendedGrantTypes: ["state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["luxury goods", "jewelry", "artisan", "craftsmanship", "export", "small business"],
    tips: ["Frame luxury goods work around artisan preservation and cultural heritage", "Export grants via SBA STEP support international market entry"],
  },
  machinery: {
    industry: "Machinery",
    painPoints: ["Advanced manufacturing grant eligibility", "Workforce training program access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["machinery", "manufacturing", "advanced manufacturing", "NIST", "DOE", "workforce"],
    tips: ["NIST MEP helps small machinery manufacturers access federal and state grants", "DOE Industrial Efficiency programs fund machinery modernization"],
  },
  maritime: {
    industry: "Maritime",
    painPoints: ["MARAD and Coast Guard grant complexity", "Port infrastructure funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["maritime", "marine", "MARAD", "Coast Guard", "port", "shipping", "vessel"],
    tips: ["MARAD Port Infrastructure Development Program funds port modernization", "IIJA created new marine highway and maritime funding streams"],
  },
  mechanical_engineering: {
    industry: "Mechanical Or Industrial Engineering",
    painPoints: ["NSF and DOE SBIR competition", "Manufacturing research grant eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["mechanical engineering", "industrial engineering", "SBIR", "NSF", "DOE", "manufacturing", "R&D"],
    tips: ["NSF Engineering SBIR solicitations are open to mechanical innovation", "DOE Advanced Manufacturing funds engineering process R&D"],
  },
  media_production: {
    industry: "Media Production",
    painPoints: ["NEA and CPB grant competition", "Local journalism and documentary funding access"],
    recommendedGrantTypes: ["foundation", "state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["media", "film", "video", "journalism", "documentary", "CPB", "NEA", "production"],
    tips: ["Sundance Institute and IDA fund documentary and independent media production", "CPB funds public media with educational and community components"],
  },
  medical_devices: {
    industry: "Medical Devices",
    painPoints: ["NIH and FDA SBIR program complexity", "Clinical validation funding gaps"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["medical devices", "FDA", "NIH", "SBIR", "clinical", "medtech", "healthcare technology"],
    tips: ["NIH SBIR/STTR is the primary path for medical device R&D funding", "State biotech and medtech consortia offer pre-SBIR support"],
  },
  medical_practice: {
    industry: "Medical Practice",
    painPoints: ["HRSA rural and underserved funding eligibility", "Healthcare quality improvement grant access"],
    recommendedGrantTypes: ["federal", "foundation", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["medical practice", "HRSA", "primary care", "rural health", "federally qualified health center", "FQHC"],
    tips: ["HRSA FQHC Look-Alike designation opens most federal health practice grants", "Rural health care grants are highly competitive for qualifying practices"],
  },
  mental_health: {
    industry: "Mental Health Care",
    painPoints: ["SAMHSA grant application complexity", "Crisis care and prevention funding access"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["mental health", "SAMHSA", "behavioral health", "crisis care", "suicide prevention", "substance use"],
    tips: ["SAMHSA is the primary federal funder of mental health programs", "State mental health authorities administer block grant funding locally"],
  },
  mining_metals: {
    industry: "Mining & Metals",
    painPoints: ["Environmental compliance grant access", "Worker safety funding navigation"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["mining", "metals", "critical minerals", "DOE", "MSHA", "worker safety", "environmental"],
    tips: ["DOE Critical Minerals program funds domestic mining for strategic materials", "MSHA Mine Safety grants fund worker training and safety programs"],
  },
  film: {
    industry: "Motion Pictures And Film",
    painPoints: ["State film incentive navigation", "Independent film foundation grant competition"],
    recommendedGrantTypes: ["state", "foundation", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["film", "cinema", "documentary", "production", "NEA", "Sundance", "state film office"],
    tips: ["State film offices provide production grants and tax incentives for qualifying projects", "NEA Our Town and documentary foundations are key federal/private funding paths"],
  },
  museums: {
    industry: "Museums And Institutions",
    painPoints: ["IMLS grant competition", "Collections care and digitization funding gaps"],
    recommendedGrantTypes: ["federal", "foundation", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["museum", "cultural institution", "IMLS", "NEA", "NEH", "collections", "digitization", "preservation"],
    tips: ["IMLS Museums for America is the primary federal grant for museums", "NEH funds humanities-focused museum exhibitions and programs"],
  },
  music: {
    industry: "Music",
    painPoints: ["NEA individual artist grant limitations", "Music education program funding access"],
    recommendedGrantTypes: ["foundation", "state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["music", "performing arts", "NEA", "state arts council", "music education", "artist"],
    tips: ["GRAMMY Foundation and music-specific foundations fund music education programs", "State arts councils are often more accessible than NEA for music projects"],
  },
  nanotechnology: {
    industry: "Nanotechnology",
    painPoints: ["NSF and NIH nanotech SBIR complexity", "Commercialization bridge funding gaps"],
    recommendedGrantTypes: ["federal"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["nanotechnology", "nanoscience", "NSF", "NIH", "SBIR", "STTR", "advanced materials"],
    tips: ["NSF's Small Business Innovation program actively funds nanotechnology R&D", "NIH SBIR funds nano-based medical applications with strong commercialization paths"],
  },
  newspapers: {
    industry: "Newspapers",
    painPoints: ["Local journalism funding scarcity", "Transition to digital sustainability"],
    recommendedGrantTypes: ["foundation", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["newspaper", "journalism", "local news", "media", "Knight Foundation", "press freedom"],
    tips: ["Knight Foundation is the leading funder of local journalism initiatives", "American Journalism Project funds sustainable local news organizations"],
  },
  nonprofit_management: {
    industry: "Non-Profit Organization Management",
    painPoints: ["Capacity-building grant access", "Overhead funding limitations"],
    recommendedGrantTypes: ["foundation", "federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["nonprofit", "capacity building", "organizational development", "leadership", "community foundation"],
    tips: ["Community foundations prioritize local nonprofit capacity building grants", "Overhead is now more fundable — use 'full cost funding' frameworks in proposals"],
  },
  oil_energy: {
    industry: "Oil & Energy",
    painPoints: ["DOE transition funding complexity", "Energy workforce grant access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["oil", "gas", "energy", "DOE", "transition", "workforce", "methane reduction"],
    tips: ["DOE funds methane reduction, efficiency, and workforce transition for energy sector", "State energy offices have transition grants for energy communities"],
  },
  online_media: {
    industry: "Online Media",
    painPoints: ["Limited traditional grant access", "Local journalism and digital access funding"],
    recommendedGrantTypes: ["foundation", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["online media", "digital journalism", "content", "social media", "digital publishing"],
    tips: ["Frame online media projects around community information access for grant eligibility", "Knight and MacArthur foundations fund digital media with civic impact"],
  },
  freight_delivery: {
    industry: "Package/Freight Delivery",
    painPoints: ["DOT and logistics grant navigation", "EV fleet transition funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["freight", "delivery", "logistics", "DOT", "EV fleet", "last-mile delivery"],
    tips: ["EPA and DOT fund last-mile and zero-emission delivery vehicle grants", "USPS and DOT rural delivery programs create opportunity in underserved areas"],
  },
  packaging: {
    industry: "Packaging And Containers",
    painPoints: ["Sustainable packaging R&D funding gaps", "Manufacturing grant eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["packaging", "containers", "sustainable", "recycling", "manufacturing", "EPA"],
    tips: ["EPA funds sustainable packaging innovation and waste reduction programs", "DOE and NIST manufacturing grants support packaging process improvements"],
  },
  paper_forest: {
    industry: "Paper & Forest Products",
    painPoints: ["USDA forestry grant navigation", "Sustainable logging and paper mill funding"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["paper", "forest products", "timber", "USDA Forest Service", "sustainable forestry"],
    tips: ["USDA Forest Service State and Private Forestry programs are accessible", "Biomass energy grants intersect with paper and forest product operations"],
  },
  performing_arts: {
    industry: "Performing Arts",
    painPoints: ["NEA grant competitiveness", "Post-pandemic recovery funding access"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["performing arts", "theater", "dance", "opera", "NEA", "state arts council", "cultural"],
    tips: ["NEA Grants for Arts Projects is the primary federal performing arts funder", "American Rescue Plan arts recovery funds are still accessible in some states"],
  },
  pharmaceuticals: {
    industry: "Pharmaceuticals",
    painPoints: ["NIH drug development grant complexity", "FDA approval and clinical trial funding gaps"],
    recommendedGrantTypes: ["federal"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["pharmaceuticals", "drug development", "NIH", "SBIR", "clinical trials", "FDA", "biopharmaceutical"],
    tips: ["NIH SBIR/STTR is the primary federal path for early-stage pharma development", "BARDA funds medical countermeasures development for biodefense applications"],
  },
  philanthropy: {
    industry: "Philanthropy",
    painPoints: ["Funding infrastructure for grant-making organizations", "IRS compliance for DAFs"],
    recommendedGrantTypes: ["foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["philanthropy", "foundation", "grantmaking", "DAF", "charitable giving"],
    tips: ["Council on Foundations and community foundation networks offer infrastructure grants", "Impact investing and PRIs offer alternative non-dilutive capital for philanthropic orgs"],
  },
  photography: {
    industry: "Photography",
    painPoints: ["Limited direct photography grants", "Documentary and arts funding access"],
    recommendedGrantTypes: ["foundation", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["photography", "visual arts", "documentary", "NEA", "state arts council", "photojournalism"],
    tips: ["State arts councils fund photography with community and cultural components", "Magnum Foundation and documentary photography foundations fund social-impact work"],
  },
  plastics: {
    industry: "Plastics",
    painPoints: ["Circular economy and recycling grant navigation", "EPA plastic pollution funding"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["plastics", "recycling", "circular economy", "EPA", "sustainability", "manufacturing"],
    tips: ["EPA funds plastic waste reduction and recycling infrastructure projects", "DOE funds bio-based plastic alternatives and manufacturing innovation"],
  },
  k12_education: {
    industry: "Primary/Secondary Education",
    painPoints: ["Title I funding formula changes", "State education grant competition"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["K-12", "education", "Title I", "Title II", "STEM", "after school", "tutoring", "school"],
    tips: ["Title I funds are allocated by formula but competitive discretionary grants exist", "21st Century Community Learning Centers fund after-school and summer programs"],
  },
  printing: {
    industry: "Printing",
    painPoints: ["Manufacturing grant eligibility limitations", "Workforce development funding access"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["printing", "print manufacturing", "commercial printing", "workforce training"],
    tips: ["NIST MEP assists printing companies in accessing manufacturing grants", "State workforce development programs fund printing industry training"],
  },
  professional_training: {
    industry: "Professional Training & Coaching",
    painPoints: ["WIOA workforce training grant eligibility", "Employer-sponsored training grant access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["professional training", "workforce development", "WIOA", "coaching", "upskilling", "career development"],
    tips: ["WIOA funds employer-driven professional training programs at scale", "ApprenticeshipUSA grants support registered apprenticeship programs"],
  },
  program_development: {
    industry: "Program Development",
    painPoints: ["Impact measurement requirements for funders", "Multi-year program funding gaps"],
    recommendedGrantTypes: ["foundation", "federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["program development", "capacity building", "nonprofit", "community programs", "social impact"],
    tips: ["Demonstrate theory of change and measurable outcomes to increase fundability", "Community foundations fund program development for locally-rooted organizations"],
  },
  public_policy: {
    industry: "Public Policy",
    painPoints: ["Think tank and research grant competition", "Issue advocacy funding restrictions"],
    recommendedGrantTypes: ["foundation", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["public policy", "policy research", "advocacy", "think tank", "government relations"],
    tips: ["Open Society Foundations and Ford Foundation are key public policy funders", "Distinguish between lobbying (restricted) and policy education (fundable)"],
  },
  public_safety: {
    industry: "Public Safety",
    painPoints: ["FEMA and DHS grant complexity", "Equipment and training funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["public safety", "emergency management", "FEMA", "fire", "EMS", "first responders", "DHS"],
    tips: ["FEMA BRIC and HMGP grants are primary mitigation funding for public safety", "AFG (Assistance to Firefighters Grants) funds equipment and training annually"],
  },
  publishing: {
    industry: "Publishing",
    painPoints: ["NEA literary arts grant competition", "Independent publisher funding access"],
    recommendedGrantTypes: ["foundation", "state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["publishing", "literary arts", "books", "NEA", "NEH", "state arts council", "independent press"],
    tips: ["NEA Big Read and literature grants fund publishing with community reach", "NEH funds scholarly and humanities-focused publishing projects"],
  },
  railroad: {
    industry: "Railroad Manufacture",
    painPoints: ["FRA grant eligibility requirements", "Rail infrastructure funding complexity"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["railroad", "rail", "FRA", "Amtrak", "freight rail", "transportation infrastructure"],
    tips: ["FRA and DOT IIJA rail grants fund manufacturing and safety improvements", "State rail programs often layer on top of federal railroad grants"],
  },
  ranching: {
    industry: "Ranching",
    painPoints: ["USDA livestock program complexity", "Conservation payment access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["ranching", "livestock", "USDA", "NRCS", "conservation", "grazing", "pasture"],
    tips: ["NRCS EQIP is the primary federal conservation payment program for ranchers", "USDA FSA Emergency programs support ranchers during drought and disaster"],
  },
  real_estate: {
    industry: "Real Estate",
    painPoints: ["Affordable housing grant eligibility", "Community development funding access"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["real estate", "affordable housing", "HUD", "LIHTC", "community development", "housing"],
    tips: ["Low Income Housing Tax Credits (LIHTC) are the largest affordable housing subsidy", "HUD HOME and CDBG funds are allocated to states and localities"],
  },
  recreation: {
    industry: "Recreational Facilities And Services",
    painPoints: ["Land and Water Conservation Fund access", "Community recreation grant eligibility"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["recreation", "parks", "outdoor", "LWCF", "community facilities", "sports"],
    tips: ["Land and Water Conservation Fund is the primary federal recreation grant", "USDA Community Facilities grants fund rural recreation infrastructure"],
  },
  religious: {
    industry: "Religious Institutions",
    painPoints: ["Separation of church and state grant restrictions", "Community service program funding access"],
    recommendedGrantTypes: ["foundation", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["faith-based", "community service", "social services", "charitable", "congregation"],
    tips: ["Faith-based organizations can access federal grants through social service programs", "Frame community programs (food pantries, shelters) separately from religious activities"],
  },
  renewables: {
    industry: "Renewables & Environment",
    painPoints: ["IRA and DOE grant program complexity", "Clean energy project financing gaps"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["renewable energy", "solar", "wind", "clean energy", "DOE", "IRA", "sustainability", "climate"],
    tips: ["IRA (Inflation Reduction Act) created the largest clean energy funding in US history", "DOE Loan Programs Office is accessible for larger renewable energy projects"],
  },
  research: {
    industry: "Research",
    painPoints: ["NIH/NSF grant application complexity", "F&A (indirect cost) rate negotiation"],
    recommendedGrantTypes: ["federal", "foundation"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["research", "R&D", "NIH", "NSF", "academia", "laboratory", "scientific", "innovation"],
    tips: ["Negotiate an F&A rate agreement before applying for federal research grants", "NIH and NSF have different review criteria — tailor proposals to each agency's priorities"],
  },
  restaurants: {
    industry: "Restaurants",
    painPoints: ["Limited direct restaurant grant access", "Minority-owned restaurant funding navigation"],
    recommendedGrantTypes: ["state", "foundation", "corporate"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["restaurant", "food service", "hospitality", "small business", "minority-owned", "culinary"],
    tips: ["James Beard Foundation and culinary foundations fund minority-owned restaurants", "State and local economic development grants support restaurant sector recovery"],
  },
  retail: {
    industry: "Retail",
    painPoints: ["Main Street revitalization grant access", "Small retailer economic development funding"],
    recommendedGrantTypes: ["state", "federal", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["retail", "small business", "Main Street", "EDA", "community development", "storefront"],
    tips: ["National Main Street Center grants support historic commercial district retailers", "EDA and CDBG funds flow through local economic development programs for retailers"],
  },
  security: {
    industry: "Security And Investigations",
    painPoints: ["DHS and CISA grant eligibility requirements", "Physical security funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["security", "investigations", "DHS", "CISA", "homeland security", "physical security"],
    tips: ["DHS Nonprofit Security Grant Program funds security upgrades for at-risk nonprofits", "State homeland security offices administer SHSP grants for physical security"],
  },
  semiconductors: {
    industry: "Semiconductors",
    painPoints: ["CHIPS Act application complexity", "R&D and manufacturing grant eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["semiconductors", "chips", "CHIPS Act", "DOC", "advanced manufacturing", "microelectronics"],
    tips: ["CHIPS and Science Act created $52B+ in direct semiconductor funding", "NIST Manufacturing USA institutes offer partnership for semiconductor innovation"],
  },
  shipbuilding: {
    industry: "Shipbuilding",
    painPoints: ["MARAD and Navy grant complexity", "Jones Act compliance and funding"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["shipbuilding", "maritime", "MARAD", "Navy", "vessels", "port", "ship repair"],
    tips: ["MARAD Title XI loan guarantees support shipbuilding financing", "DoD and Navy R&D contracts are major funding sources for shipyards"],
  },
  sporting_goods: {
    industry: "Sporting Goods",
    painPoints: ["Limited direct sporting goods grants", "Youth sports and recreation funding access"],
    recommendedGrantTypes: ["foundation", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["sporting goods", "sports", "recreation", "youth sports", "athletics", "outdoor"],
    tips: ["Frame sporting goods work around youth development and health to access foundation grants", "Dick's Sporting Goods Foundation and Nike grants support youth sports access"],
  },
  sports: {
    industry: "Sports",
    painPoints: ["Youth sports access and equity grant navigation", "Sports facility infrastructure funding"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["sports", "athletics", "youth sports", "recreation", "fitness", "community sports"],
    tips: ["USDA Community Facilities and EDA grants fund sports infrastructure in rural/underserved areas", "Robert Wood Johnson Foundation funds sports and health equity programs"],
  },
  supermarkets: {
    industry: "Supermarkets",
    painPoints: ["USDA healthy food financing eligibility", "Food desert access grant navigation"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["supermarket", "grocery", "food access", "food desert", "USDA", "healthy food financing"],
    tips: ["USDA Healthy Food Financing Initiative funds grocery access in underserved areas", "CDFI loans and grants support supermarket development in food deserts"],
  },
  telecommunications: {
    industry: "Telecommunications",
    painPoints: ["NTIA broadband program complexity", "Universal Service Fund navigation"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["telecommunications", "broadband", "NTIA", "FCC", "connectivity", "wireless", "5G"],
    tips: ["NTIA BEAD program is $42.5B for broadband expansion — largest telecom funding ever", "FCC E-Rate and Connect America Fund support telecom access programs"],
  },
  textiles: {
    industry: "Textiles",
    painPoints: ["Advanced textile manufacturing grant access", "Workforce development funding"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["textiles", "fabric", "apparel", "manufacturing", "technical textiles", "workforce"],
    tips: ["DOD funds advanced textile innovation for military and defense applications", "NIST MEP assists textile manufacturers in accessing manufacturing grants"],
  },
  think_tanks: {
    industry: "Think Tanks",
    painPoints: ["Policy research foundation grant competition", "501(c)(3) grant restriction navigation"],
    recommendedGrantTypes: ["foundation", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["think tank", "policy research", "public policy", "research", "advocacy", "social science"],
    tips: ["Distinguish education from lobbying carefully in grant proposals", "Smith Richardson and Bradley foundations fund domestic policy research"],
  },
  translation: {
    industry: "Translation And Localization",
    painPoints: ["Limited direct grant access", "Language access program funding"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["translation", "localization", "language access", "interpretation", "multilingual", "LEP"],
    tips: ["Federal LEP (Limited English Proficiency) requirements create translation grant opportunities", "State and local government language access programs fund translation services"],
  },
  transportation: {
    industry: "Transportation/Trucking/Railroad",
    painPoints: ["DOT grant eligibility complexity", "EV fleet transition funding navigation"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["transportation", "trucking", "freight", "DOT", "EV", "fleet electrification", "IIJA"],
    tips: ["IIJA created $1.2T in transportation funding — largest opportunity in decades", "DOT's Rebuilding American Infrastructure with Sustainability and Equity (RAISE) is highly competitive but large"],
  },
  utilities: {
    industry: "Utilities",
    painPoints: ["DOE grid modernization grant complexity", "Rural utility funding access"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["utilities", "energy", "grid", "DOE", "USDA RUS", "rural utilities", "smart grid"],
    tips: ["USDA Rural Utilities Service funds rural electric, water, and telecom utilities", "DOE Grid Resilience grants are accessible to qualifying utilities"],
  },
  veterinary: {
    industry: "Veterinary",
    painPoints: ["USDA Animal and Plant Health funding access", "Veterinary workforce grant eligibility"],
    recommendedGrantTypes: ["federal", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["veterinary", "animal health", "USDA APHIS", "veterinary workforce", "zoonotic disease"],
    tips: ["USDA APHIS funds veterinary services in underserved and rural areas", "AVMA Foundation and state vet associations fund workforce development"],
  },
  warehousing: {
    industry: "Warehousing",
    painPoints: ["Workforce training grant eligibility", "Supply chain grant access limitations"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["warehousing", "logistics", "supply chain", "workforce training", "distribution"],
    tips: ["State workforce boards fund warehousing and logistics sector training", "DOT supply chain grants support warehousing infrastructure in key corridors"],
  },
  wholesale: {
    industry: "Wholesale",
    painPoints: ["Limited direct wholesale grants", "Economic development funding access"],
    recommendedGrantTypes: ["state", "federal"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["wholesale", "distribution", "trade", "small business", "economic development"],
    tips: ["SBA programs support wholesale operations in underserved markets", "Export promotion grants are available for wholesale companies entering global markets"],
  },
  wine_spirits: {
    industry: "Wine And Spirits",
    painPoints: ["USDA specialty crop grant access", "Agritourism funding eligibility"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["wine", "spirits", "distillery", "winery", "USDA", "specialty crop", "agritourism"],
    tips: ["USDA Specialty Crop Block Grants fund wine and spirits research and marketing", "State agricultural programs support wine and spirits industry development"],
  },
  wireless: {
    industry: "Wireless",
    painPoints: ["FCC and NTIA grant application complexity", "Rural wireless infrastructure funding"],
    recommendedGrantTypes: ["federal", "state"],
    recommendedServiceTier: "readiness_audit",
    grantKeywords: ["wireless", "broadband", "5G", "FCC", "NTIA", "spectrum", "mobile connectivity"],
    tips: ["NTIA BEAD and Middle Mile programs fund wireless infrastructure expansion", "FCC E-Rate program funds wireless connectivity for schools and libraries"],
  },
  other: {
    industry: "Other",
    painPoints: ["Identifying the right grant programs", "Navigating cross-sector funding opportunities"],
    recommendedGrantTypes: ["federal", "state", "foundation"],
    recommendedServiceTier: "grant_strategy",
    grantKeywords: ["small business", "economic development", "community", "innovation"],
    tips: ["A grant strategy session helps identify your best-fit funding programs", "SBA, EDA, and community foundation grants are often accessible regardless of sector"],
  },
};

/**
 * Look up the industry profile for a given industry key.
 * Returns null if not found.
 */
export function getIndustryProfile(industryKey: string | null | undefined): IndustryProfile | null {
  if (!industryKey) return null;
  return INDUSTRY_PROFILES[industryKey] ?? null;
}

/**
 * Build an industry context string for injection into AI prompts.
 */
export function buildIndustryContext(industryKey: string | null | undefined): string {
  const profile = getIndustryProfile(industryKey);
  if (!profile) return "";

  return [
    "### Industry Context",
    `Industry: ${profile.industry}`,
    `Key Pain Points: ${profile.painPoints.join("; ")}`,
    `Priority Grant Types: ${profile.recommendedGrantTypes.join(", ")}`,
    `Boost Keywords: ${profile.grantKeywords.join(", ")}`,
  ].join("\n");
}
