"use client";

// Review-gated copy/export button. Before the user can copy or
// download an AI-generated draft, a modal appears asking them to
// affirm they have reviewed the content and take responsibility
// for its accuracy. Closes P1-4 of the legal audit on AI output
// liability allocation.
//
// Acknowledgment is logged server-side with timestamp, IP, UA,
// and a content hash. One acknowledgment per draft per browser
// session — after the first Copy All of a session, subsequent
// copies skip the modal (cached in sessionStorage).

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Check, Copy, AlertTriangle } from "lucide-react";

interface ReviewGateButtonProps {
  text: string;
  draftId: string;
  label?: string;
  action?: "copy_all" | "copy_section" | "download_docx" | "download_pdf";
}

function sessionKey(draftId: string) {
  return `gq_review_ack_${draftId}`;
}

async function computeHash(text: string): Promise<string | null> {
  try {
    const encoder = new TextEncoder();
    const buf = encoder.encode(text);
    const digest = await crypto.subtle.digest("SHA-256", buf);
    return Array.from(new Uint8Array(digest))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
  } catch {
    return null;
  }
}

export function ReviewGateButton({
  text,
  draftId,
  label = "Copy All",
  action = "copy_all",
}: ReviewGateButtonProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [checked, setChecked] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  async function doCopy() {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API not available — silently ignore.
    }
  }

  async function handleClick() {
    // Skip the modal if the user already acknowledged this draft
    // in this browser session. Keeps friction low after the first
    // confirmation.
    if (typeof window !== "undefined" && sessionStorage.getItem(sessionKey(draftId))) {
      await doCopy();
      return;
    }
    setOpen(true);
  }

  async function handleConfirm() {
    if (!checked) return;
    setSubmitting(true);
    try {
      const content_hash = await computeHash(text);
      await fetch(`/api/writing/${draftId}/acknowledge-review`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action, content_hash }),
      });
    } catch {
      // Fail-open: don't block the user from copying their own content
      // if the acknowledgment write fails. The server-side endpoint
      // also fails open.
    }
    if (typeof window !== "undefined") {
      sessionStorage.setItem(sessionKey(draftId), new Date().toISOString());
    }
    setOpen(false);
    setSubmitting(false);
    setChecked(false);
    await doCopy();
  }

  return (
    <>
      <Button variant="outline" size="sm" onClick={handleClick}>
        {copied ? (
          <>
            <Check className="h-3.5 w-3.5" />
            Copied
          </>
        ) : (
          <>
            <Copy className="h-3.5 w-3.5" />
            {label}
          </>
        )}
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <div className="flex items-start gap-3">
              <AlertTriangle
                className="h-5 w-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5"
                aria-hidden="true"
              />
              <div>
                <DialogTitle>Confirm review before copying</DialogTitle>
                <DialogDescription className="mt-2 leading-relaxed">
                  This draft was generated by AI. Before you submit it to a
                  funder, you are responsible for reviewing every section for
                  accuracy, truthfulness, and alignment with your
                  organization&apos;s work. AI content may contain errors or
                  hallucinated facts.
                </DialogDescription>
              </div>
            </div>
          </DialogHeader>

          <label className="flex items-start gap-2 mt-4 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="mt-0.5 h-4 w-4 shrink-0 cursor-pointer rounded border border-input accent-[var(--color-brand-teal)]"
            />
            <span className="text-sm text-warm-700 dark:text-warm-300 leading-snug">
              <strong>I have reviewed this draft</strong> and take
              responsibility for its accuracy before submitting it to any
              funder. I understand GrantAQ does not guarantee funding and that
              AI-generated content is my responsibility to verify.
            </span>
          </label>

          <DialogFooter className="mt-4 flex-col sm:flex-row gap-2">
            <Button
              variant="outline"
              onClick={() => {
                setOpen(false);
                setChecked(false);
              }}
              disabled={submitting}
            >
              Cancel
            </Button>
            <Button
              onClick={handleConfirm}
              disabled={!checked || submitting}
              className="!bg-brand-teal hover:!bg-brand-teal-dark !text-white"
            >
              {submitting ? "Recording…" : "I confirm — continue"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
