"use client";

import { useState, useEffect } from "react";
import { Loader2 } from "lucide-react";

/**
 * Print-friendly report page. Fetches the latest diagnostic report
 * and renders the full_report_markdown as styled HTML for Save as PDF.
 */
export default function ReportPage() {
  const [markdown, setMarkdown] = useState<string | null>(null);
  const [companyName, setCompanyName] = useState("Organization");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch("/api/services/orders?type=readiness_diagnostic");
        if (res.ok) {
          const data = await res.json();
          const order = data.orders?.[0];
          if (order?.report_data?.full_report_markdown) {
            setMarkdown(order.report_data.full_report_markdown);
          }
          if (order?.report_data?.executive_summary?.summary) {
            // Try to get company name from the report
            const match = (order.report_data.full_report_markdown as string)?.match(/Prepared for:\s*(.+)/i);
            if (match) setCompanyName(match[1].trim());
          }
        }
      } catch {
        // ignore
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  useEffect(() => {
    if (markdown && !loading) {
      // Auto-trigger print dialog after a short delay
      setTimeout(() => window.print(), 500);
    }
  }, [markdown, loading]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-6 w-6 animate-spin" />
      </div>
    );
  }

  if (!markdown) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <p className="text-muted-foreground">No diagnostic report found. Run the full diagnostic first.</p>
      </div>
    );
  }

  // Convert markdown to simple HTML (basic conversion)
  const html = markdownToHtml(markdown);

  return (
    <>
      <style jsx global>{`
        @media print {
          nav, aside, header, .no-print { display: none !important; }
          body { background: white !important; }
          .print-container { max-width: 100% !important; padding: 0 !important; }
        }
        .report-content h1 { font-size: 24px; font-weight: 700; margin: 24px 0 12px; border-bottom: 2px solid #0D9488; padding-bottom: 8px; }
        .report-content h2 { font-size: 20px; font-weight: 700; margin: 20px 0 10px; color: #1C1917; }
        .report-content h3 { font-size: 16px; font-weight: 600; margin: 16px 0 8px; }
        .report-content p { margin: 8px 0; line-height: 1.6; }
        .report-content ul, .report-content ol { margin: 8px 0; padding-left: 24px; }
        .report-content li { margin: 4px 0; line-height: 1.5; }
        .report-content table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
        .report-content th { background: #F5F5F4; padding: 8px; text-align: left; border: 1px solid #E7E5E4; font-weight: 600; }
        .report-content td { padding: 8px; border: 1px solid #E7E5E4; }
        .report-content strong { font-weight: 600; }
        .report-content hr { border: none; border-top: 1px solid #E7E5E4; margin: 20px 0; }
        .report-content blockquote { border-left: 3px solid #0D9488; padding-left: 16px; margin: 12px 0; color: #44403C; }
      `}</style>

      <div className="print-container max-w-3xl mx-auto px-6 py-8">
        {/* Header — branded */}
        <div className="flex items-center justify-between mb-8 border-b-2 border-[#0D9488] pb-4">
          <div>
            <h1 className="text-2xl font-bold" style={{ color: "#0D9488" }}>GrantAQ</h1>
            <p className="text-xs text-gray-500">AI-Powered Grant Discovery & Strategy</p>
          </div>
          <div className="text-right">
            <p className="text-sm font-medium">{companyName}</p>
            <p className="text-xs text-gray-500">{new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
          </div>
        </div>

        {/* Report content */}
        <div
          className="report-content text-sm text-gray-800"
          dangerouslySetInnerHTML={{ __html: html }}
        />

        {/* Footer */}
        <div className="mt-12 pt-4 border-t border-gray-200 text-xs text-gray-400 text-center">
          <p>Generated by GrantAQ · grantaq.com · {new Date().toISOString().split("T")[0]}</p>
          <p className="mt-1">This is a Grant Readiness & Eligibility Diagnostic. It is not a substitute for a licensed CPA-performed financial audit.</p>
        </div>

        {/* Print button — hidden when printing */}
        <div className="no-print fixed bottom-6 right-6">
          <button
            onClick={() => window.print()}
            className="bg-[#0D9488] text-white px-6 py-3 rounded-lg font-medium shadow-lg hover:bg-[#0B7C71]"
          >
            Save as PDF
          </button>
        </div>
      </div>
    </>
  );
}

/** Basic markdown → HTML converter */
function markdownToHtml(md: string): string {
  let html = md
    // Headings
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    // Bold
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    // Italic
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Horizontal rules
    .replace(/^---$/gm, "<hr>")
    // Blockquotes
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    // Unordered lists
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    // Ordered lists
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
    // Paragraphs (lines not already tagged)
    .replace(/^(?!<[hluob]|<li|<hr)(.*\S.*)$/gm, "<p>$1</p>");

  // Wrap consecutive <li> in <ul>
  html = html.replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`);

  return html;
}
