/**
 * Complete service catalog for GrantAQ.
 * Single source of truth for all services, pricing, and descriptions.
 */

export interface ServiceDef {
  id: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  price: string;
  priceNote?: string;
  category: "free" | "subscription" | "one_time" | "per_grant" | "add_on";
  tier?: string;
  deliveryTime: string;
  deliverables: string[];
  targetCustomer: string;
  conversionPath: string;
  icon: string; // lucide icon name
  href: string;
  isBuilt: boolean;
}

export const SERVICE_CATALOG: ServiceDef[] = [
  // ── FREE SERVICES (Lead Magnets) ──
  {
    id: "eligibility_check",
    name: "Free Grant Eligibility Check",
    shortName: "Eligibility Check",
    description: "Instant AI assessment of your grant readiness — no account needed.",
    longDescription: "Answer 3 pages of questions and get an instant AI-powered eligibility verdict. See which grants you qualify for, what's blocking you, and quick wins you can act on this week.",
    price: "Free",
    category: "free",
    deliveryTime: "Instant (30 seconds)",
    deliverables: ["Eligibility verdict", "Grant categories", "Top blockers", "Quick wins", "Grant universe estimate"],
    targetCustomer: "Anyone curious about grants",
    conversionPath: "Check → Signup → Diagnostic → Service purchase",
    icon: "ClipboardCheck",
    href: "/check",
    isBuilt: true,
  },
  {
    id: "eligibility_status",
    name: "Grant Eligibility Status",
    shortName: "Eligibility Status",
    description: "Quick AI assessment of whether your organization qualifies for grants.",
    longDescription: "Analyzes your org profile against federal, state, foundation, and corporate grant requirements. Returns verdict, eligible categories, blockers with fixes, and demographic eligibility.",
    price: "Free",
    priceNote: "Included with account",
    category: "free",
    deliveryTime: "Instant",
    deliverables: ["Eligibility verdict", "9 category breakdown", "Blockers with severity", "Quick wins", "Demographic eligibility matrix"],
    targetCustomer: "Signed-up users",
    conversionPath: "Status → Full diagnostic → Service tiers",
    icon: "CheckCircle",
    href: "/services/eligibility-status",
    isBuilt: true,
  },
  {
    id: "readiness_diagnostic",
    name: "Grant Eligibility & Readiness Diagnostic",
    shortName: "Readiness Diagnostic",
    description: "Comprehensive 10-step AI diagnostic for first-time grant seekers.",
    longDescription: "5-layer readiness audit, COSO internal controls, site-visit simulation, funder matching, remediation roadmap. Every gap includes what to do, where, who, cost, and which service tier covers it.",
    price: "Free",
    priceNote: "1 free, unlimited with subscription",
    category: "free",
    deliveryTime: "30 seconds",
    deliverables: ["5-layer audit", "Red flag screen", "COSO controls score", "Audit simulation", "4 scored dimensions", "Funder matches", "Remediation roadmap", "Service recommendation"],
    targetCustomer: "Signed-up users considering services",
    conversionPath: "Diagnostic → Every gap points to Tier 1/2/3",
    icon: "FileSearch",
    href: "/services/readiness-diagnostic",
    isBuilt: true,
  },

  // ── SUBSCRIPTIONS ──
  {
    id: "seeker",
    name: "Seeker Plan",
    shortName: "Seeker",
    description: "Full grant library, pipeline tracking, and calendar.",
    longDescription: "Browse 6,300+ grants, track up to 10 in your pipeline, access the grant calendar, store 5 documents, and chat with Grantie 15 times per day.",
    price: "$39/mo",
    priceNote: "$390/yr (save 17%)",
    category: "subscription",
    tier: "starter",
    deliveryTime: "Instant access",
    deliverables: ["Full grant library", "10 pipeline slots", "Calendar", "5 vault docs", "15 AI chats/day"],
    targetCustomer: "Small orgs exploring grants",
    conversionPath: "Free → Seeker (pipeline fills up at 3)",
    icon: "Search",
    href: "/upgrade",
    isBuilt: true,
  },
  {
    id: "strategist",
    name: "Strategist Plan",
    shortName: "Strategist",
    description: "Unlimited matching, analytics, and document vault.",
    longDescription: "Unlimited scorecard, document vault (20 docs), 30 AI chats/day, analytics dashboard, A-Z qualification tracking, and unlimited readiness scores.",
    price: "$99/mo",
    priceNote: "$950/yr (save 20%)",
    category: "subscription",
    tier: "pro",
    deliveryTime: "Instant access",
    deliverables: ["Unlimited scorecard", "20 vault docs", "30 chats/day", "Analytics", "A-Z tracking"],
    targetCustomer: "Active grant seekers",
    conversionPath: "Seeker → Strategist (needs analytics + vault)",
    icon: "BarChart",
    href: "/upgrade",
    isBuilt: true,
  },
  {
    id: "applicant",
    name: "Applicant Plan",
    shortName: "Applicant",
    description: "AI grant writing, expert review, and unlimited everything.",
    longDescription: "AI writing engine (5 drafts/mo), expert review option, unlimited pipeline, narrative memory, and full document vault.",
    price: "$179/mo",
    priceNote: "$1,710/yr (save 20%)",
    category: "subscription",
    tier: "growth",
    deliveryTime: "Instant access",
    deliverables: ["5 AI drafts/mo", "Expert review", "Unlimited pipeline", "Narrative memory", "Full vault"],
    targetCustomer: "Orgs ready to write applications",
    conversionPath: "Strategist → Applicant (wants to write grants)",
    icon: "PenLine",
    href: "/upgrade",
    isBuilt: true,
  },
  {
    id: "organization",
    name: "Organization Plan",
    shortName: "Organization",
    description: "Everything plus dedicated writer, team access, API, and CSM.",
    longDescription: "Full platform access for unlimited team members, dedicated grant writer, API access, white-label exports, and customer success manager.",
    price: "$349/mo",
    priceNote: "$3,350/yr (save 20%)",
    category: "subscription",
    tier: "enterprise",
    deliveryTime: "Instant + CSM onboarding",
    deliverables: ["Everything", "Unlimited team", "Dedicated writer", "API access", "White-label", "CSM"],
    targetCustomer: "Teams and consultants",
    conversionPath: "Applicant → Organization (multiple users)",
    icon: "Building2",
    href: "/upgrade",
    isBuilt: true,
  },

  // ── ONE-TIME SERVICES ──
  {
    id: "tier1_review",
    name: "Tier 1 — Readiness & Eligibility Review",
    shortName: "Readiness Review",
    description: "Full diagnostic with a 45-minute expert walkthrough call.",
    longDescription: "Everything in the AI diagnostic plus a 45-minute call with a grant strategist who walks through every finding, answers questions, and recommends next steps.",
    price: "$497",
    category: "one_time",
    deliveryTime: "5-7 business days",
    deliverables: ["Full AI diagnostic", "45-min walkthrough call", "Personalized recommendations", "Recording of call"],
    targetCustomer: "Orgs who want expert guidance on their diagnostic",
    conversionPath: "Diagnostic → Tier 1 (want human explanation)",
    icon: "UserCheck",
    href: "/services",
    isBuilt: true,
  },
  {
    id: "tier2_roadmap",
    name: "Tier 2 — Readiness + Remediation Roadmap",
    shortName: "Remediation Roadmap",
    description: "Step-by-step playbook to become grant-ready in 2-3 weeks.",
    longDescription: "Full diagnostic + remediation playbook with templates, vendor directory, funder-matched target list, 2 strategy calls (60 min each), and 30-day email support.",
    price: "$1,997",
    category: "one_time",
    deliveryTime: "2-3 weeks",
    deliverables: ["Full diagnostic", "Remediation playbook", "Policy templates", "Vendor directory", "Funder target list", "2 strategy calls", "30-day support"],
    targetCustomer: "Orgs serious about becoming grant-ready",
    conversionPath: "Tier 1 → Tier 2 (want the roadmap executed)",
    icon: "Map",
    href: "/services",
    isBuilt: true,
  },
  {
    id: "tier3_accelerator",
    name: "Tier 3 — Readiness Accelerator",
    shortName: "Readiness Accelerator",
    description: "60-120 day done-for-you engagement with first application drafted.",
    longDescription: "Everything in Tier 2 plus: SAM/UEI registration completed, all policies drafted, logic model built, indirect cost rate election, capability statement, first starter-grant application drafted, weekly sessions.",
    price: "$4,997",
    category: "one_time",
    deliveryTime: "60-120 days",
    deliverables: ["Everything in Tier 2", "SAM/UEI done-for-you", "Policies drafted", "Logic model", "Capability statement", "First application drafted", "Weekly sessions"],
    targetCustomer: "$500K+ revenue orgs who value time over money",
    conversionPath: "Tier 2 → Tier 3 (want someone to do it for them)",
    icon: "Rocket",
    href: "/services",
    isBuilt: true,
  },
  {
    id: "restructuring",
    name: "Strategic Restructuring Engagement",
    shortName: "Restructuring",
    description: "For 'Not Eligible' verdicts — structural fit analysis + alternative capital roadmap.",
    longDescription: "2-4 week engagement: structural fit analysis, restructuring options (501c3, fiscal sponsorship, reincorporation), alternative capital roadmap (R&D credits, SBA loans, CDFI), 60-min strategy call.",
    price: "$1,497",
    category: "one_time",
    deliveryTime: "2-4 weeks",
    deliverables: ["Structural analysis", "Restructuring options table", "Alternative capital roadmap", "60-min strategy call", "Decision-ready recommendation"],
    targetCustomer: "Orgs told 'not eligible' who want a path forward",
    conversionPath: "Diagnostic (not eligible) → Restructuring",
    icon: "RefreshCw",
    href: "/services",
    isBuilt: true,
  },
  {
    id: "starter_grant_package",
    name: "Starter Grant Application Package",
    shortName: "Starter Grants",
    description: "We write and prepare 3-5 starter grant applications for you.",
    longDescription: "AI writes and prepares applications for 3-5 first-timer-friendly grants (Amber Grant, Hello Alice, Comcast RISE, local community foundations). Builds track record with small wins.",
    price: "$299",
    category: "one_time",
    deliveryTime: "7-10 business days",
    deliverables: ["3-5 completed applications", "Submission instructions per grant", "Follow-up tracking checklist"],
    targetCustomer: "First-time seekers who need to build track record",
    conversionPath: "Diagnostic → Starter Package → Writing tiers for bigger grants",
    icon: "Award",
    href: "/services/starter-grants",
    isBuilt: false,
  },
  {
    id: "nonprofit_formation",
    name: "501(c)(3) Formation Assistance",
    shortName: "Nonprofit Formation",
    description: "Guided nonprofit formation with AI-generated documents and IRS prep.",
    longDescription: "AI generates formation checklist, articles of incorporation template, bylaws template, Form 1023/1023-EZ prep guide, EIN application guide, and state registration checklist. Includes review call.",
    price: "$1,500-$3,500",
    category: "one_time",
    deliveryTime: "2-4 weeks (docs), 3-9 months (IRS approval)",
    deliverables: ["Formation checklist", "Articles template", "Bylaws template", "Form 1023 prep guide", "EIN guide", "State registration guide", "Review call"],
    targetCustomer: "Entrepreneurs starting a nonprofit",
    conversionPath: "Homepage 'Start a Nonprofit' → Formation service → Grant platform subscription",
    icon: "Building",
    href: "/services/nonprofit-formation",
    isBuilt: false,
  },
  {
    id: "sam_registration",
    name: "SAM.gov Registration Service",
    shortName: "SAM Registration",
    description: "We handle your complete SAM.gov registration — the #1 federal grant blocker.",
    longDescription: "Done-for-you SAM.gov and UEI registration. We handle the application, IRS validation issues, CAGE code, and entity management. Most common blocker for federal grants.",
    price: "$750-$1,500",
    category: "one_time",
    deliveryTime: "2-6 weeks (IRS validation dependent)",
    deliverables: ["UEI obtained", "SAM.gov registration active", "CAGE code assigned", "Registration confirmation", "Annual renewal reminder set"],
    targetCustomer: "Orgs blocked by SAM in diagnostic",
    conversionPath: "Diagnostic → 'SAM not registered' blocker → SAM service",
    icon: "Shield",
    href: "/services/sam-registration",
    isBuilt: false,
  },
  {
    id: "policy_drafting",
    name: "Grant Policy Drafting Package",
    shortName: "Policy Package",
    description: "AI-customized grant compliance policies your org needs.",
    longDescription: "AI generates all required grant policies customized to your organization: Conflict of Interest, Whistleblower, Document Retention, Drug-Free Workplace, Procurement (2 CFR 200), Code of Ethics, Travel, Timekeeping.",
    price: "$500-$1,000",
    category: "one_time",
    deliveryTime: "3-5 business days",
    deliverables: ["8 customized policies", "Board resolution templates", "Annual signing forms", "Implementation guide"],
    targetCustomer: "Orgs with policy gaps in diagnostic",
    conversionPath: "Diagnostic → 'missing policies' gaps → Policy package",
    icon: "FileText",
    href: "/services/policy-drafting",
    isBuilt: false,
  },
  {
    id: "application_review",
    name: "Grant Application Review",
    shortName: "App Review",
    description: "Expert AI + human review of your completed grant application.",
    longDescription: "Upload your completed application. AI scores it against funder criteria and common failure points. Expert reviewer provides feedback on narrative strength, compliance, budget alignment, and competitiveness.",
    price: "$199-$499",
    priceNote: "$199 state/foundation, $499 federal",
    category: "one_time",
    deliveryTime: "3-5 business days",
    deliverables: ["Compliance score", "Narrative strength assessment", "Budget review", "Specific improvement suggestions", "Competitiveness rating"],
    targetCustomer: "Orgs who wrote their own application and want review",
    conversionPath: "Lower barrier than writing — they wrote it, we review it",
    icon: "Eye",
    href: "/services/application-review",
    isBuilt: false,
  },
  {
    id: "logic_model",
    name: "Logic Model & Theory of Change Builder",
    shortName: "Logic Model",
    description: "AI builds your project logic model and theory of change.",
    longDescription: "AI generates a complete logic model (inputs, activities, outputs, outcomes, impact) and theory of change from your project description. Required for most federal and foundation grants.",
    price: "$99",
    priceNote: "Included in Tier 2/3",
    category: "add_on",
    deliveryTime: "Instant (AI-generated)",
    deliverables: ["Logic model diagram", "Theory of change narrative", "SMART objectives", "KPI framework", "Evaluation plan outline"],
    targetCustomer: "Orgs preparing grant applications",
    conversionPath: "Diagnostic → 'no logic model' gap → Logic model builder",
    icon: "GitBranch",
    href: "/services/logic-model",
    isBuilt: false,
  },
  {
    id: "audit_prep",
    name: "Compliance Audit Preparation",
    shortName: "Audit Prep",
    description: "Prepare for a funder site visit or compliance audit.",
    longDescription: "Pre-audit checklist, document assembly guide, and mock site-visit simulation using your diagnostic data. Know exactly what a funder will ask for and whether you can produce it.",
    price: "$497",
    category: "one_time",
    deliveryTime: "5-7 business days",
    deliverables: ["Pre-audit checklist", "Document assembly guide", "Mock site-visit Q&A", "Gap remediation list", "30-day action plan"],
    targetCustomer: "Orgs with active grants facing funder review",
    conversionPath: "Portfolio tracker shows upcoming audit → Audit prep service",
    icon: "ClipboardList",
    href: "/services/audit-prep",
    isBuilt: false,
  },
  {
    id: "certification",
    name: "Grant-Ready Certification",
    shortName: "Certification",
    description: "Official badge verifying your organization is grant-ready.",
    longDescription: "After completing Tier 2 or Tier 3, receive a Grant-Ready Certified badge with verification URL. Display on your website for funder credibility. Valid for 1 year — annual renewal drives re-engagement.",
    price: "Included in Tier 2/3",
    priceNote: "$249/yr renewal",
    category: "add_on",
    deliveryTime: "Issued upon Tier 2/3 completion",
    deliverables: ["Certified badge image", "Verification URL (/certified/[code])", "Embeddable badge code", "Certificate PDF"],
    targetCustomer: "Orgs completing Tier 2/3",
    conversionPath: "Tier 2/3 → Certification → Annual renewal revenue + free marketing",
    icon: "Award",
    href: "/certified",
    isBuilt: false,
  },

  // ── PER-GRANT WRITING ──
  {
    id: "writing_ai",
    name: "AI Grant Writing",
    shortName: "AI Writing",
    description: "AI drafts your grant application with compliance checking.",
    longDescription: "AI generates a complete grant application draft based on your org profile, the grant requirements, and funder priorities. Includes compliance check against common failure points.",
    price: "$149-$499",
    priceNote: "$149 state/foundation, $349 federal, $499 SBIR",
    category: "per_grant",
    deliveryTime: "Instant (AI-generated)",
    deliverables: ["Complete draft", "Compliance check", "Budget template", "Submission instructions"],
    targetCustomer: "Applicant/Organization tier subscribers",
    conversionPath: "Subscription → Match → Write",
    icon: "PenLine",
    href: "/writing",
    isBuilt: true,
  },
  {
    id: "writing_audit",
    name: "AI + Expert Audit Writing",
    shortName: "AI + Audit",
    description: "AI draft reviewed and improved by a human grant expert.",
    longDescription: "AI generates the initial draft, then a human grant expert reviews for narrative strength, funder alignment, and compliance. One round of revisions included.",
    price: "$249-$749",
    priceNote: "$249 state, $549 federal, $749 SBIR",
    category: "per_grant",
    deliveryTime: "3-5 business days",
    deliverables: ["AI draft", "Expert review notes", "Revised draft", "Compliance certification"],
    targetCustomer: "Orgs wanting quality assurance",
    conversionPath: "AI writing → upgrade to audit for important grants",
    icon: "FileCheck",
    href: "/writing",
    isBuilt: true,
  },
  {
    id: "writing_expert",
    name: "Expert-Led Grant Writing",
    shortName: "Expert Writing",
    description: "Professional grant writer with AI tools and 2 revision rounds.",
    longDescription: "A professional grant writer drafts your application using AI tools for research and compliance. Two full revision rounds. Best for competitive federal grants.",
    price: "$499-$1,749",
    priceNote: "$499 state, $1,249 federal, $1,749 SBIR",
    category: "per_grant",
    deliveryTime: "7-14 business days",
    deliverables: ["Expert-written draft", "AI compliance check", "2 revision rounds", "Final submission-ready package"],
    targetCustomer: "Orgs applying to competitive grants",
    conversionPath: "AI writing → expert for high-stakes applications",
    icon: "Pen",
    href: "/writing",
    isBuilt: true,
  },
  {
    id: "writing_full_confidence",
    name: "Full Confidence Package",
    shortName: "Full Confidence",
    description: "$0 upfront — we only get paid if you win the grant (3-10% success fee).",
    longDescription: "We write the full application at no upfront cost. If you win, we earn 3-10% of the award amount (based on your tier and grant size). If you don't win, you pay nothing.",
    price: "$0 upfront",
    priceNote: "3-10% success fee on award",
    category: "per_grant",
    deliveryTime: "14-21 business days",
    deliverables: ["Full application", "Budget narrative", "Supporting documents", "Submission support", "Post-submission tracking"],
    targetCustomer: "Orgs confident in their eligibility who want zero risk",
    conversionPath: "Diagnostic (eligible) → Full Confidence",
    icon: "Zap",
    href: "/writing",
    isBuilt: true,
  },
];

export function getServicesByCategory(category: ServiceDef["category"]): ServiceDef[] {
  return SERVICE_CATALOG.filter((s) => s.category === category);
}

export function getBuiltServices(): ServiceDef[] {
  return SERVICE_CATALOG.filter((s) => s.isBuilt);
}

export function getUnbuiltServices(): ServiceDef[] {
  return SERVICE_CATALOG.filter((s) => !s.isBuilt);
}
